### ISSUE TITLE
error while show labels for 2d detection

### ISSUE THREAD

**Issue by renping0535** [ucbdrive/bdd100k#87]
I am trying to get a visualization about the 2d detection box according to the demo, but I got this error:
(perception) renping@msi:~/000/bdd100k$ python -m bdd100k.show_labels --image-dir /home/renping/000/Images/train -l /home/renping/000/Annotations/train.json
Image: 0000f77c-6257be58.jpg
Traceback (most recent call last):
  File "/opt/Anaconda3/envs/perception/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/Anaconda3/envs/perception/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/renping/000/bdd100k/bdd100k/show_labels.py", line 899, in <module>
    main()
  File "/home/renping/000/bdd100k/bdd100k/show_labels.py", line 895, in main
    viewer.view()
  File "/home/renping/000/bdd100k/bdd100k/show_labels.py", line 550, in view
    self.show()
  File "/home/renping/000/bdd100k/bdd100k/show_labels.py", line 563, in show
    self.show_image()
  File "/home/renping/000/bdd100k/bdd100k/show_labels.py", line 698, in show_image
    if b['attributes']['Occluded']:
KeyError: 'Occluded'

any suggestion or advice?

By the way, in the 100K images, for 70k training images, we only have 69863 annotations, how to handle the left 137 labels?

Thanks in advance.

**Comment by Clement-W** [comment]
Hi,
This error is occurring because the first letter of the key 'occluded' and 'truncated' are written in uppercase in the script show_labels.py.
In the JSON file, those key are in lowercase and the key 'crowd' doesn't exist. :
```
"attributes": {
        "occluded": false,
        "truncated": false,
        "trafficLightColor": "green"
}
```

At line 698, changing this :
```
                    if b['attributes']['Occluded']:
                        text += ',o'
                    if b['attributes']['Truncated']:
                        text += ',t'
                    if b['attributes']['Crowd']:
                        text += ',c'
```
to this :
```
                    if b['attributes']['occluded']:
                        text += ',o'
                    if b['attributes']['truncated']:
                        text += ',t'
```
should fix the error.

**Comment by fyu** [comment]
@Clement-W Thanks for the suggestion. I commit the fix in this PR: https://github.com/ucbdrive/bdd100k/pull/90
